### ISSUE TITLE
from pysdd.sdd import SddManager, Vtree, WmcManager returns No module named pysdd

### ISSUE THREAD

**Issue by ntpapatheodorou** [wannesm/PySDD#22]
Using Ubuntu and Python 3.8 _(installed Cython and PySDD via pip)_ when im trying to import _(from pysdd.sdd import SddManager, Vtree, WmcManager)_ it returns the error "_No module named pysdd_"

**Comment by VincentDerk** [comment]
Did you check the output printed during installation for any errors?

You can also look at previous (resolved) issues and see if those solutions work for you. For example: https://github.com/wannesm/PySDD/issues/18#issuecomment-584913547

**Comment by ntpapatheodorou** [comment]
_Requirement already satisfied: PySDD from git+https://github.com/wannesm/PySDD.git#egg=PySDD in /usr/local/lib/python3.8/dist-packages (0.2.10)
Requirement already satisfied: cython>=0.29.6 in /usr/local/lib/python3.8/dist-packages (from PySDD) (0.29.21)_

**Comment by VincentDerk** [comment]
The installation process includes a compilation step. If the compilation fails, for example because of some missing dependencies, this is not always recognised by the installation process. This means your python distribution will think it is installed but it actually didn't install properly. That is why you need to uninstall it first, or use flags such as `--upgrade --force-reinstall` to force the reinstallation.

**Comment by ntpapatheodorou** [comment]
Solved.
Can you please send me a private email ? I want to ask you something about a work of mine which I need to use PySDD with Problog
